export interface CountryCode {
  name: string;
  code: string;
  iso: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { name: 'Ecuador', code: '+593', iso: 'EC' },
  { name: 'Afganistán', code: '+93', iso: 'AF' },
  { name: 'Albania', code: '+355', iso: 'AL' },
  { name: 'Alemania', code: '+49', iso: 'DE' },
  { name: 'Andorra', code: '+376', iso: 'AD' },
  { name: 'Angola', code: '+244', iso: 'AO' },
  { name: 'Antigua y Barbuda', code: '+1-268', iso: 'AG' },
  { name: 'Arabia Saudita', code: '+966', iso: 'SA' },
  { name: 'Argelia', code: '+213', iso: 'DZ' },
  { name: 'Argentina', code: '+54', iso: 'AR' },
  { name: 'Armenia', code: '+374', iso: 'AM' },
  { name: 'Australia', code: '+61', iso: 'AU' },
  { name: 'Austria', code: '+43', iso: 'AT' },
  { name: 'Azerbaiyán', code: '+994', iso: 'AZ' },
  { name: 'Bahamas', code: '+1-242', iso: 'BS' },
  { name: 'Bangladés', code: '+880', iso: 'BD' },
  { name: 'Barbados', code: '+1-246', iso: 'BB' },
  { name: 'Baréin', code: '+973', iso: 'BH' },
  { name: 'Bélgica', code: '+32', iso: 'BE' },
  { name: 'Belice', code: '+501', iso: 'BZ' },
  { name: 'Benín', code: '+229', iso: 'BJ' },
  { name: 'Bielorrusia', code: '+375', iso: 'BY' },
  { name: 'Birmania', code: '+95', iso: 'MM' },
  { name: 'Bolivia', code: '+591', iso: 'BO' },
  { name: 'Bosnia y Herzegovina', code: '+387', iso: 'BA' },
  { name: 'Botsuana', code: '+267', iso: 'BW' },
  { name: 'Brasil', code: '+55', iso: 'BR' },
  { name: 'Brunéi', code: '+673', iso: 'BN' },
  { name: 'Bulgaria', code: '+359', iso: 'BG' },
  { name: 'Burkina Faso', code: '+226', iso: 'BF' },
  { name: 'Burundi', code: '+257', iso: 'BI' },
  { name: 'Bután', code: '+975', iso: 'BT' },
  { name: 'Cabo Verde', code: '+238', iso: 'CV' },
  { name: 'Camboya', code: '+855', iso: 'KH' },
  { name: 'Camerún', code: '+237', iso: 'CM' },
  { name: 'Canadá', code: '+1', iso: 'CA' },
  { name: 'Catar', code: '+974', iso: 'QA' },
  { name: 'Chad', code: '+235', iso: 'TD' },
  { name: 'Chile', code: '+56', iso: 'CL' },
  { name: 'China', code: '+86', iso: 'CN' },
  { name: 'Chipre', code: '+357', iso: 'CY' },
  { name: 'Colombia', code: '+57', iso: 'CO' },
  { name: 'Comoras', code: '+269', iso: 'KM' },
  { name: 'Corea del Norte', code: '+850', iso: 'KP' },
  { name: 'Corea del Sur', code: '+82', iso: 'KR' },
  { name: 'Costa de Marfil', code: '+225', iso: 'CI' },
  { name: 'Costa Rica', code: '+506', iso: 'CR' },
  { name: 'Croacia', code: '+385', iso: 'HR' },
  { name: 'Cuba', code: '+53', iso: 'CU' },
  { name: 'Dinamarca', code: '+45', iso: 'DK' },
  { name: 'Dominica', code: '+1-767', iso: 'DM' },
  { name: 'Egipto', code: '+20', iso: 'EG' },
  { name: 'El Salvador', code: '+503', iso: 'SV' },
  { name: 'Emiratos Árabes Unidos', code: '+971', iso: 'AE' },
  { name: 'Eritrea', code: '+291', iso: 'ER' },
  { name: 'Eslovaquia', code: '+421', iso: 'SK' },
  { name: 'Eslovenia', code: '+386', iso: 'SI' },
  { name: 'España', code: '+34', iso: 'ES' },
  { name: 'Estados Unidos', code: '+1', iso: 'US' },
  { name: 'Estonia', code: '+372', iso: 'EE' },
  { name: 'Esuatini', code: '+268', iso: 'SZ' },
  { name: 'Etiopía', code: '+251', iso: 'ET' },
  { name: 'Filipinas', code: '+63', iso: 'PH' },
  { name: 'Finlandia', code: '+358', iso: 'FI' },
  { name: 'Fiyi', code: '+679', iso: 'FJ' },
  { name: 'Francia', code: '+33', iso: 'FR' },
  { name: 'Gabón', code: '+241', iso: 'GA' },
  { name: 'Gambia', code: '+220', iso: 'GM' },
  { name: 'Georgia', code: '+995', iso: 'GE' },
  { name: 'Ghana', code: '+233', iso: 'GH' },
  { name: 'Granada', code: '+1-473', iso: 'GD' },
  { name: 'Grecia', code: '+30', iso: 'GR' },
  { name: 'Guatemala', code: '+502', iso: 'GT' },
  { name: 'Guinea', code: '+224', iso: 'GN' },
  { name: 'Guinea-Bisáu', code: '+245', iso: 'GW' },
  { name: 'Guinea Ecuatorial', code: '+240', iso: 'GQ' },
  { name: 'Guyana', code: '+592', iso: 'GY' },
  { name: 'Haití', code: '+509', iso: 'HT' },
  { name: 'Honduras', code: '+504', iso: 'HN' },
  { name: 'Hungría', code: '+36', iso: 'HU' },
  { name: 'India', code: '+91', iso: 'IN' },
  { name: 'Indonesia', code: '+62', iso: 'ID' },
  { name: 'Irak', code: '+964', iso: 'IQ' },
  { name: 'Irán', code: '+98', iso: 'IR' },
  { name: 'Irlanda', code: '+353', iso: 'IE' },
  { name: 'Islandia', code: '+354', iso: 'IS' },
  { name: 'Islas Marshall', code: '+692', iso: 'MH' },
  { name: 'Islas Salomón', code: '+677', iso: 'SB' },
  { name: 'Israel', code: '+972', iso: 'IL' },
  { name: 'Italia', code: '+39', iso: 'IT' },
  { name: 'Jamaica', code: '+1-876', iso: 'JM' },
  { name: 'Japón', code: '+81', iso: 'JP' },
  { name: 'Jordania', code: '+962', iso: 'JO' },
  { name: 'Kazajistán', code: '+7', iso: 'KZ' },
  { name: 'Kenia', code: '+254', iso: 'KE' },
  { name: 'Kirguistán', code: '+996', iso: 'KG' },
  { name: 'Kiribati', code: '+686', iso: 'KI' },
  { name: 'Kuwait', code: '+965', iso: 'KW' },
  { name: 'Laos', code: '+856', iso: 'LA' },
  { name: 'Letonia', code: '+371', iso: 'LV' },
  { name: 'Líbano', code: '+961', iso: 'LB' },
  { name: 'Liberia', code: '+231', iso: 'LR' },
  { name: 'Libia', code: '+218', iso: 'LY' },
  { name: 'Liechtenstein', code: '+423', iso: 'LI' },
  { name: 'Lituania', code: '+370', iso: 'LT' },
  { name: 'Luxemburgo', code: '+352', iso: 'LU' },
  { name: 'Madagascar', code: '+261', iso: 'MG' },
  { name: 'Malasia', code: '+60', iso: 'MY' },
  { name: 'Malaui', code: '+265', iso: 'MW' },
  { name: 'Maldivas', code: '+960', iso: 'MV' },
  { name: 'Malí', code: '+223', iso: 'ML' },
  { name: 'Malta', code: '+356', iso: 'MT' },
  { name: 'Marruecos', code: '+212', iso: 'MA' },
  { name: 'Mauricio', code: '+230', iso: 'MU' },
  { name: 'Mauritania', code: '+222', iso: 'MR' },
  { name: 'México', code: '+52', iso: 'MX' },
  { name: 'Micronesia', code: '+691', iso: 'FM' },
  { name: 'Moldavia', code: '+373', iso: 'MD' },
  { name: 'Mónaco', code: '+377', iso: 'MC' },
  { name: 'Mongolia', code: '+976', iso: 'MN' },
  { name: 'Montenegro', code: '+382', iso: 'ME' },
  { name: 'Mozambique', code: '+258', iso: 'MZ' },
  { name: 'Namibia', code: '+264', iso: 'NA' },
  { name: 'Nauru', code: '+674', iso: 'NR' },
  { name: 'Nepal', code: '+977', iso: 'NP' },
  { name: 'Nicaragua', code: '+505', iso: 'NI' },
  { name: 'Níger', code: '+227', iso: 'NE' },
  { name: 'Nigeria', code: '+234', iso: 'NG' },
  { name: 'Noruega', code: '+47', iso: 'NO' },
  { name: 'Nueva Zelanda', code: '+64', iso: 'NZ' },
  { name: 'Omán', code: '+968', iso: 'OM' },
  { name: 'Países Bajos', code: '+31', iso: 'NL' },
  { name: 'Pakistán', code: '+92', iso: 'PK' },
  { name: 'Palaos', code: '+680', iso: 'PW' },
  { name: 'Panamá', code: '+507', iso: 'PA' },
  { name: 'Papúa Nueva Guinea', code: '+675', iso: 'PG' },
  { name: 'Paraguay', code: '+595', iso: 'PY' },
  { name: 'Perú', code: '+51', iso: 'PE' },
  { name: 'Polonia', code: '+48', iso: 'PL' },
  { name: 'Portugal', code: '+351', iso: 'PT' },
  { name: 'Reino Unido', code: '+44', iso: 'GB' },
  { name: 'República Centroafricana', code: '+236', iso: 'CF' },
  { name: 'República Checa', code: '+420', iso: 'CZ' },
  { name: 'República del Congo', code: '+242', iso: 'CG' },
  { name: 'República Democrática del Congo', code: '+243', iso: 'CD' },
  { name: 'República Dominicana', code: '+1-809', iso: 'DO' },
  { name: 'Ruanda', code: '+250', iso: 'RW' },
  { name: 'Rumanía', code: '+40', iso: 'RO' },
  { name: 'Rusia', code: '+7', iso: 'RU' },
  { name: 'Samoa', code: '+685', iso: 'WS' },
  { name: 'San Cristóbal y Nieves', code: '+1-869', iso: 'KN' },
  { name: 'San Marino', code: '+378', iso: 'SM' },
  { name: 'San Vicente y las Granadinas', code: '+1-784', iso: 'VC' },
  { name: 'Santa Lucía', code: '+1-758', iso: 'LC' },
  { name: 'Santo Tomé y Príncipe', code: '+239', iso: 'ST' },
  { name: 'Senegal', code: '+221', iso: 'SN' },
  { name: 'Serbia', code: '+381', iso: 'RS' },
  { name: 'Seychelles', code: '+248', iso: 'SC' },
  { name: 'Sierra Leona', code: '+232', iso: 'SL' },
  { name: 'Singapur', code: '+65', iso: 'SG' },
  { name: 'Siria', code: '+963', iso: 'SY' },
  { name: 'Somalia', code: '+252', iso: 'SO' },
  { name: 'Sri Lanka', code: '+94', iso: 'LK' },
  { name: 'Sudáfrica', code: '+27', iso: 'ZA' },
  { name: 'Sudán', code: '+249', iso: 'SD' },
  { name: 'Sudán del Sur', code: '+211', iso: 'SS' },
  { name: 'Suecia', code: '+46', iso: 'SE' },
  { name: 'Suiza', code: '+41', iso: 'CH' },
  { name: 'Surinam', code: '+597', iso: 'SR' },
  { name: 'Tailandia', code: '+66', iso: 'TH' },
  { name: 'Tanzania', code: '+255', iso: 'TZ' },
  { name: 'Tayikistán', code: '+992', iso: 'TJ' },
  { name: 'Timor Oriental', code: '+670', iso: 'TL' },
  { name: 'Togo', code: '+228', iso: 'TG' },
  { name: 'Tonga', code: '+676', iso: 'TO' },
  { name: 'Trinidad y Tobago', code: '+1-868', iso: 'TT' },
  { name: 'Túnez', code: '+216', iso: 'TN' },
  { name: 'Turkmenistán', code: '+993', iso: 'TM' },
  { name: 'Turquía', code: '+90', iso: 'TR' },
  { name: 'Tuvalu', code: '+688', iso: 'TV' },
  { name: 'Ucrania', code: '+380', iso: 'UA' },
  { name: 'Uganda', code: '+256', iso: 'UG' },
  { name: 'Uruguay', code: '+598', iso: 'UY' },
  { name: 'Uzbekistán', code: '+998', iso: 'UZ' },
  { name: 'Vanuatu', code: '+678', iso: 'VU' },
  { name: 'Vaticano', code: '+379', iso: 'VA' },
  { name: 'Venezuela', code: '+58', iso: 'VE' },
  { name: 'Vietnam', code: '+84', iso: 'VN' },
  { name: 'Yemen', code: '+967', iso: 'YE' },
  { name: 'Yibuti', code: '+253', iso: 'DJ' },
  { name: 'Zambia', code: '+260', iso: 'ZM' },
  { name: 'Zimbabue', code: '+263', iso: 'ZW' }
];


export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  AF: ['Kabul', 'Herat', 'Kandahar', 'Mazar-i-Sharif'],
  AL: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'],
  DE: ['Berlín', 'Múnich', 'Hamburgo', 'Fráncfort'],
  AD: ['Andorra la Vella', 'Escaldes-Engordany'],
  AO: ['Luanda', 'Huambo', 'Benguela', 'Lubango'],
  AG: ['Saint John’s'],
  SA: ['Riad', 'Yeda', 'Dammam', 'Medina'],
  DZ: ['Argel', 'Orán', 'Constantina', 'Annaba'],
  AR: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'],
  AM: ['Ereván', 'Gyumri', 'Vanadzor'],
  AU: ['Sídney', 'Melbourne', 'Brisbane', 'Perth'],
  AT: ['Viena', 'Graz', 'Linz', 'Salzburgo'],
  AZ: ['Bakú', 'Ganja', 'Sumqayit'],
  BS: ['Nassau', 'Freeport'],
  BD: ['Daca', 'Chittagong', 'Khulna'],
  BB: ['Bridgetown'],
  BH: ['Manama', 'Muharraq'],
  BE: ['Bruselas', 'Amberes', 'Gante', 'Lieja'],
  BZ: ['Ciudad de Belice', 'San Ignacio', 'Belmopán'],
  BJ: ['Porto-Novo', 'Cotonú', 'Parakou'],
  BY: ['Minsk', 'Gómel', 'Moguiliov'],
  MM: ['Naypyidó', 'Yangón', 'Mandalay'],
  BO: ['La Paz', 'Santa Cruz', 'Cochabamba'],
  BA: ['Sarajevo', 'Bania Luka', 'Mostar'],
  BW: ['Gaborone', 'Francistown'],
  BR: ['São Paulo', 'Río de Janeiro', 'Brasilia', 'Salvador'],
  BN: ['Bandar Seri Begawan'],
  BG: ['Sofía', 'Plovdiv', 'Varna'],
  BF: ['Uagadugú', 'Bobo-Diulaso'],
  BI: ['Buyumbura', 'Gitega'],
  BT: ['Thimbu', 'Phuentsholing'],
  CV: ['Praia', 'Mindelo'],
  KH: ['Nom Pen', 'Siem Reap', 'Battambang'],
  CM: ['Yaundé', 'Dualá'],
  CA: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
  QA: ['Doha'],
  TD: ['Yamena', 'Moundou'],
  CL: ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta'],
  CN: ['Pekín', 'Shanghái', 'Cantón', 'Shenzhen'],
  CY: ['Nicosia', 'Limassol', 'Lárnaca'],
  CO: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'],
  KM: ['Moroni'],
  KP: ['Pionyang', 'Hamhung'],
  KR: ['Seúl', 'Busan', 'Incheon'],
  CI: ['Abiyán', 'Yamusukro'],
  CR: ['San José', 'Alajuela', 'Cartago'],
  HR: ['Zagreb', 'Split', 'Dubrovnik'],
  CU: ['La Habana', 'Santiago de Cuba', 'Camagüey'],
  DK: ['Copenhague', 'Aarhus', 'Odense'],
  DM: ['Roseau'],
  EC: ['Quito', 'Guayaquil', 'Cuenca', 'Portoviejo'],
  EG: ['El Cairo', 'Alejandría', 'Giza', 'Luxor'],
  SV: ['San Salvador', 'Santa Ana', 'Soyapango'],
  AE: ['Dubái', 'Abu Dabi', 'Sharjah'],
  ER: ['Asmara'],
  SK: ['Bratislava', 'Košice'],
  SI: ['Liubliana', 'Maribor'],
  ES: ['Madrid', 'Barcelona', 'Valencia', 'Sevilla'],
  US: ['New York', 'Los Angeles', 'Miami', 'Chicago'],
  EE: ['Tallin', 'Tartu'],
  SZ: ['Mbabane', 'Manzini'],
  ET: ['Adís Abeba', 'Dire Dawa'],
  PH: ['Manila', 'Cebú', 'Dávao'],
  FI: ['Helsinki', 'Espoo', 'Tampere'],
  FJ: ['Suva', 'Nadi'],
  FR: ['París', 'Lyon', 'Marsella', 'Toulouse'],
  GA: ['Libreville', 'Port-Gentil'],
  GM: ['Banjul', 'Serrekunda'],
  GE: ['Tiflis', 'Batumi', 'Kutaisi'],
  GH: ['Acra', 'Kumasi'],
  GD: ['Saint George’s'],
  GR: ['Atenas', 'Tesalónica'],
  GT: ['Ciudad de Guatemala', 'Antigua Guatemala', 'Quetzaltenango'],
  GN: ['Conakry', 'Kankan'],
  GW: ['Bissau'],
  GQ: ['Malabo', 'Bata'],
  GY: ['Georgetown', 'Linden'],
  HT: ['Puerto Príncipe', 'Cap-Haïtien'],
  HN: ['Tegucigalpa', 'San Pedro Sula'],
  HU: ['Budapest', 'Debrecen', 'Szeged'],
  IN: ['Nueva Delhi', 'Mumbai', 'Bangalore', 'Chennai'],
  ID: ['Yakarta', 'Surabaya', 'Bandung'],
  IQ: ['Bagdad', 'Basora', 'Mosul'],
  IR: ['Teherán', 'Mashhad', 'Isfahán'],
  IE: ['Dublín', 'Cork', 'Galway'],
  IS: ['Reikiavik'],
  MH: ['Majuro'],
  SB: ['Honiara'],
  IL: ['Jerusalén', 'Tel Aviv', 'Haifa'],
  IT: ['Roma', 'Milán', 'Nápoles', 'Turín'],
  JM: ['Kingston', 'Montego Bay'],
  JP: ['Tokio', 'Osaka', 'Kioto', 'Nagoya'],
  JO: ['Ammán', 'Zarqa'],
  KZ: ['Almatý', 'Astaná', 'Shymkent'],
  KE: ['Nairobi', 'Mombasa', 'Kisumu'],
  KG: ['Biskek', 'Osh'],
  KI: ['Tarawa'],
  KW: ['Ciudad de Kuwait'],
  LA: ['Vientián', 'Luang Prabang'],
  LV: ['Riga', 'Daugavpils'],
  LB: ['Beirut', 'Trípoli'],
  LR: ['Monrovia'],
  LY: ['Trípoli', 'Bengasi'],
  LI: ['Vaduz'],
  LT: ['Vilna', 'Kaunas'],
  LU: ['Ciudad de Luxemburgo'],
  MG: ['Antananarivo', 'Toamasina'],
  MY: ['Kuala Lumpur', 'George Town', 'Johor Bahru'],
  MW: ['Lilongüe', 'Blantyre'],
  MV: ['Malé'],
  ML: ['Bamako', 'Sikasso'],
  MT: ['La Valeta', 'Birkirkara'],
  MA: ['Casablanca', 'Marrakech', 'Rabat'],
  MU: ['Port Louis', 'Curepipe'],
  MR: ['Nuakchot'],
  MX: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Puebla'],
  FM: ['Palikir'],
  MD: ['Chisináu', 'Bălți'],
  MC: ['Mónaco'],
  MN: ['Ulán Bator'],
  ME: ['Podgorica', 'Nikšić'],
  MZ: ['Maputo', 'Beira'],
  NA: ['Windhoek', 'Walvis Bay'],
  NR: ['Yaren'],
  NP: ['Katmandú', 'Pokhara'],
  NI: ['Managua', 'León', 'Granada'],
  NE: ['Niamey', 'Zinder'],
  NG: ['Lagos', 'Abuya', 'Kano'],
  NO: ['Oslo', 'Bergen', 'Trondheim'],
  NZ: ['Auckland', 'Wellington', 'Christchurch'],
  OM: ['Mascate', 'Salalah'],
  NL: ['Ámsterdam', 'Róterdam', 'La Haya'],
  PK: ['Islamabad', 'Karachi', 'Lahore'],
  PW: ['Ngerulmud'],
  PA: ['Ciudad de Panamá', 'Colón'],
  PG: ['Port Moresby', 'Lae'],
  PY: ['Asunción', 'Ciudad del Este'],
  PE: ['Lima', 'Arequipa', 'Cusco', 'Trujillo'],
  PL: ['Varsovia', 'Cracovia', 'Gdansk'],
  PT: ['Lisboa', 'Oporto', 'Coímbra'],
  GB: ['Londres', 'Manchester', 'Liverpool', 'Birmingham'],
  CF: ['Bangui'],
  CZ: ['Praga', 'Brno', 'Ostrava'],
  CG: ['Brazzaville', 'Pointe-Noire'],
  CD: ['Kinshasa', 'Lubumbashi'],
  DO: ['Santo Domingo', 'Santiago de los Caballeros'],
  RW: ['Kigali'],
  RO: ['Bucarest', 'Cluj-Napoca'],
  RU: ['Moscú', 'San Petersburgo', 'Novosibirsk'],
  WS: ['Apia'],
  KN: ['Basseterre'],
  SM: ['San Marino'],
  VC: ['Kingstown'],
  LC: ['Castries'],
  ST: ['Santo Tomé'],
  SN: ['Dakar'],
  RS: ['Belgrado', 'Novi Sad'],
  SC: ['Victoria'],
  SL: ['Freetown'],
  SG: ['Singapur'],
  SY: ['Damasco', 'Alepo'],
  SO: ['Mogadiscio'],
  LK: ['Colombo', 'Kandy'],
  ZA: ['Johannesburgo', 'Ciudad del Cabo', 'Durban'],
  SD: ['Jartum', 'Omdurmán'],
  SS: ['Yuba'],
  SE: ['Estocolmo', 'Gotemburgo', 'Malmö'],
  CH: ['Zúrich', 'Ginebra', 'Basilea'],
  SR: ['Paramaribo'],
  TH: ['Bangkok', 'Chiang Mai'],
  TZ: ['Dodoma', 'Dar es Salaam'],
  TJ: ['Dusambé'],
  TL: ['Dili'],
  TG: ['Lomé'],
  TO: ['Nukualofa'],
  TT: ['Puerto España', 'San Fernando'],
  TN: ['Túnez', 'Sfax'],
  TM: ['Asjabad'],
  TR: ['Estambul', 'Ankara', 'Esmirna'],
  TV: ['Funafuti'],
  UA: ['Kiev', 'Járkov', 'Odesa'],
  UG: ['Kampala', 'Entebbe'],
  UY: ['Montevideo', 'Punta del Este'],
  UZ: ['Tashkent', 'Samarcanda'],
  VU: ['Port Vila'],
  VA: ['Ciudad del Vaticano'],
  VE: ['Caracas', 'Maracaibo', 'Valencia'],
  VN: ['Hanói', 'Ciudad Ho Chi Minh'],
  YE: ['Saná', 'Adén'],
  DJ: ['Yibuti'],
  ZM: ['Lusaka', 'Ndola'],
  ZW: ['Harare', 'Bulawayo'],
};

