export interface CountryCode {
  name: string;
  code: string; 
  iso: string;  
}

export const COUNTRY_CODES: CountryCode[] = [
  { name: 'Ecuador', code: '+593', iso: 'EC' },
  { name: 'Estados Unidos', code: '+1', iso: 'US' },
  { name: 'Colombia', code: '+57', iso: 'CO' },
  { name: 'Perú', code: '+51', iso: 'PE' },
  { name: 'México', code: '+52', iso: 'MX' },
  { name: 'Argentina', code: '+54', iso: 'AR' },
  { name: 'Chile', code: '+56', iso: 'CL' },
  { name: 'Brasil', code: '+55', iso: 'BR' },
  { name: 'Bolivia', code: '+591', iso: 'BO' },
  { name: 'Uruguay', code: '+598', iso: 'UY' },
  { name: 'Paraguay', code: '+595', iso: 'PY' },
  { name: 'Venezuela', code: '+58', iso: 'VE' },
  { name: 'España', code: '+34', iso: 'ES' },
  { name: 'Canadá', code: '+1', iso: 'CA' },
  { name: 'Reino Unido', code: '+44', iso: 'GB' },
  { name: 'Italia', code: '+39', iso: 'IT' },
  { name: 'Francia', code: '+33', iso: 'FR' },
  { name: 'Alemania', code: '+49', iso: 'DE' },
  { name: 'Portugal', code: '+351', iso: 'PT' },
  { name: 'Japón', code: '+81', iso: 'JP' },
  { name: 'Corea del Sur', code: '+82', iso: 'KR' },
  { name: 'China', code: '+86', iso: 'CN' },
];

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  EC: ['Alausí',
    'Ambato',
    'Bahía de Caráquez',
    'Babahoyo',
    'Balzar',
    'Calceta',
    'Cañar',
    'Cariamanga',
    'Catamayo',
    'Cayambe',
    'Chone',
    'Colimes',
    'Cuenca',
    'Durán',
    'El Coca',
    'El Empalme',
    'El Triunfo',
    'Esmeraldas',
    'Guaranda',
    'Guayaquil',
    'Huaquillas',
    'Ibarra',
    'Jipijapa',
    'La Libertad',
    'La Troncal',
    'Latacunga',
    'Loja',
    'Macas',
    'Manta',
    'Machala',
    'Milagro',
    'Montecristi',
    'Naranjal',
    'Naranjito',
    'Nueva Loja',
    'Otavalo',
    'Palestina',
    'Pasaje',
    'Pedro Carbo',
    'Pelileo',
    'Píllaro',
    'Playas',
    'Playas Villamil',
    'Portoviejo',
    'Puerto López',
    'Puerto Quito',
    'Pujilí',
    'Puyo',
    'Quevedo',
    'Quito',
    'Riobamba',
    'Rocafuerte',
    'Salinas',
    'Salitre',
    'San Lorenzo',
    'Santa Ana',
    'Santa Elena',
    'Santa Rosa',
    'Samborondón',
    'Saraguro',
    'Sucre',
    'Santo Domingo',
    'Tena',
    'Tulcán',
    'Valencia',
    'Ventanas',
    'Vinces',
    'Yaguachi',
    'Zamora'],
  US: ['Atlanta',
    'Boston',
    'Chicago',
    'Dallas',
    'Denver',
    'Honolulu',
    'Houston',
    'Las Vegas',
    'Los Angeles',
    'Miami',
    'New Orleans',
    'New York',
    'Orlando',
    'Philadelphia',
    'Phoenix',
    'San Antonio',
    'San Diego',
    'San Francisco',
    'Seattle',
    'Washington D.C.'],
  CO: ['Armenia',
  'Barranquilla',
  'Bucaramanga',
  'Cali',
  'Cartagena',
  'Cúcuta',
  'Ibagué',
  'Leticia',
  'Manizales',
  'Medellín',
  'Montería',
  'Neiva',
  'Pasto',
  'Pereira',
  'Popayán',
  'Riohacha',
  'Santa Marta',
  'Sincelejo',
  'Tunja',
  'Villavicencio'],
  PE: ['Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Callao',
  'Chachapoyas',
  'Chiclayo',
  'Chimbote',
  'Cusco',
  'Huancayo',
  'Huánuco',
  'Ica',
  'Iquitos',
  'Juliaca',
  'Lambayeque',
  'Lima',
  'Moquegua',
  'Piura',
  'Pucallpa',
  'Tacna',
  'Trujillo'],
  MX: ['Ciudad de México', 'Guadalajara', 'Monterrey'],
  AR: ['Bahía Blanca',
  'Bariloche',
  'Buenos Aires',
  'Cafayate',
  'Córdoba',
  'El Calafate',
  'El Chaltén',
  'La Plata',
  'Mar del Plata',
  'Mendoza',
  'Neuquén',
  'Puerto Iguazú',
  'Puerto Madryn',
  'Rosario',
  'Salta',
  'San Carlos de Bariloche',
  'San Juan',
  'San Luis',
  'San Miguel de Tucumán',
  'Ushuaia'],
  CL: ['Antofagasta',
  'Arica',
  'Calama',
  'Castro',
  'Chillán',
  'Coquimbo',
  'Copiapó',
  'La Serena',
  'Osorno',
  'Puerto Montt',
  'Puerto Natales',
  'Pucón',
  'Punta Arenas',
  'Quillota',
  'Rancagua',
  'San Antonio',
  'Santiago',
  'Talca',
  'Temuco',
  'Valparaíso'],
  BR: ['Belém',
  'Belo Horizonte',
  'Brasilia',
  'Campinas',
  'Cuiabá',
  'Curitiba',
  'Florianópolis',
  'Fortaleza',
  'Foz do Iguaçu',
  'João Pessoa',
  'Maceió',
  'Manaus',
  'Natal',
  'Porto Alegre',
  'Recife',
  'Ribeirão Preto',
  'Rio de Janeiro',
  'Salvador',
  'São Luís',
  'São Paulo'],
  BO: ['La Paz', 'Santa Cruz', 'Cochabamba'],
  UY: ['Artigas',
  'Canelones',
  'Carmelo',
  'Colonia del Sacramento',
  'Durazno',
  'Fray Bentos',
  'La Paloma',
  'La Pedrera',
  'Las Piedras',
  'Maldonado',
  'Mercedes',
  'Minas',
  'Montevideo',
  'Pando',
  'Piriápolis',
  'Punta del Este',
  'Rivera',
  'Rocha',
  'Salto',
  'Tacuarembó'],
  PY: ['Asunción', 'Ciudad del Este'],
  VE: ['Caracas', 'Maracaibo'],
  ES: ['A Coruña',
  'Alicante',
  'Barcelona',
  'Bilbao',
  'Cádiz',
  'Córdoba',
  'Girona',
  'Granada',
  'Ibiza',
  'Las Palmas de Gran Canaria',
  'Madrid',
  'Málaga',
  'Murcia',
  'Pamplona',
  'Salamanca',
  'San Sebastián',
  'Santander',
  'Sevilla',
  'Toledo',
  'Valencia'],
  CA: ['Toronto', 'Vancouver', 'Montreal'],
  GB: ['Londres', 'Manchester', 'Liverpool'],
  IT: ['Roma', 'Milán', 'Nápoles'],
  FR: ['París', 'Lyon', 'Marsella'],
  DE: ['Berlín', 'Múnich', 'Hamburgo'],
  PT: ['Lisboa', 'Oporto'],
  JP: ['Tokio', 'Osaka', 'Kioto'],
  KR: ['Seúl', 'Busan'],
  CN: ['Pekín', 'Shanghái', 'Cantón'],
};